### PR TITLE
Newsletter popup for all users

### PR DESCRIPTION
**Pull request by allanlasser**
This adds a newsletter popup that appears for all users until it is submitted or declined. The component will record a submission or declination to `localStorage`, and as long as a value exists will not appear again.

Screenshot 2024-08-29 at 1 41 53 PM

### CODE REVIEW

**Comment by amandabee** [comment]
We don't need to name Election SOS.

Currently, we ask this on the verification from:
image

Can we get close to that? 
"Stay up to date! Subscribe to make sure you get updates about the Knight Election Hub" and have check boxes for updates about the hub and MuckRock's weekly newsletter?

**Comment by allanlasser** [comment]
> Can we get close to that? "Stay up to date! Subscribe to make sure you get updates about the Knight Election Hub" and have check boxes for updates about the hub and MuckRock's weekly newsletter?

Sure, we can have some checkboxes, although the flow is slightly different. Should it be that the user is subscribing to updates about the Hub, with a checkbox to also receive MuckRock's weekly newsletter? And should the default be checked or unchecked?

**Comment by amandabee** [comment]
One version is: 
Stay up to date! Subscribe now to ensure that you'll get updates about the hub and essential tools to help you cover the 2024 elections."

**Comment by allanlasser** [comment]
Screenshot 2024-08-29 at 2 26 27 PM

Updated copy

**Comment by allanlasser** [comment]
Screenshot 2024-08-29 at 4 09 05 PM

More (final?) copy changes

**Pull request merged**
